FROM php:7.2-apache
RUN apt-get update
RUN apt-get -y install apache2-utils libaprutil1-dbd-mysql && a2enmod authn_dbd
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli 
RUN pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis
EXPOSE 80