version: '3'

services:
  db:
    image: mysql:8.0.30
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
  php:
    volumes:
      - ./src/dynamic:/var/www/html
    build: .
    ports:
      - "8081:80"
    links:
     - db
  nginx:
    image: nginx:1.23.1
    volumes:
      - ./src/templates:/usr/share/nginx/html
    ports:
      - "8082:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

volumes:
  db_volume: