version: '3'

services:
  php:
    volumes:
      - ./src:/var/www/html
      - ./conf/apache2/default.conf:/etc/apache2/sites-enabled/000-default.conf
    build: .
    ports:
      - "8084:80"
  nginx:
    image: nginx:1.23.1
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8083:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    links:
      - php